package:
  name: ocelot
  version: '25.06.0'

source:
  git_rev: 25.06.0
  git_url: https://github.com/ocelot-collab/ocelot.git

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9
    - scipy
    - matplotlib
    - pandas
  run:
    - python
    - numpy >=1.9
    - scipy


about:
  home: https://github.com/ocelot-collab/ocelot
  license: GNU General Public License v3.0
  license_file: LICENSE