package:
  name: ocelot
  version: '24.03.0'

source:
  git_rev: 24.03.0
  git_url: https://github.com/ocelot-collab/ocelot.git

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9
    - scipy
    - matplotlib
    - pandas
    - alabaster==0.7.12
    - Sphinx==3.2.1
    - sphinxcontrib-jsmath==1.0.1
  run:
    - python
    - numpy >=1.9
    - scipy


about:
  home: https://github.com/ocelot-collab/ocelot
  license: GNU General Public License v3.0
  license_file: LICENSE